import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // OpenNext (Cloudflare Workers) build output:
    ".open-next/**",
    // Local git worktrees (gitignored siblings of the main checkout):
    ".worktrees/**",
    // Auto-generated by `wrangler types` — emits its own (sometimes stale)
    // eslint-disable comments that we can't usefully maintain.
    "cloudflare-env.d.ts",
  ]),
]);

export default eslintConfig;
