// Custom Worker entry that composes OpenNext's default fetch handler
// with a scheduled handler for D1 cleanup.
// @ts-ignore — this module is generated by opennextjs-cloudflare build
import handler from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
  async scheduled(
    _controller: ScheduledController,
    env: CloudflareEnv,
    _ctx: ExecutionContext,
  ) {
    // Call our own cleanup endpoint, authenticated with CRON_SECRET.
    const res = await fetch(
      `https://${env.NEXT_PUBLIC_ROOT_DOMAIN}/api/cron/cleanup-pending`,
      {
        method: "POST",
        headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      },
    );
    if (!res.ok) {
      console.error("cleanup-pending failed", res.status, await res.text());
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
